name: Auto Generate V2Ray Configs

on:
  workflow_dispatch:

jobs:
  generate_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        run: python generate.py

      - name: Commit and push generated configs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add v2ray_configs.txt
          git commit -m 'Auto generate V2Ray configs'
          git push
